FROM alpine:latest
MAINTAINER Adrian Dvergsdal [atmoz.net]
USER root

# Steps done in one RUN layer:
# - Install packages
# - OpenSSH needs /var/run/sshd to run
# - Remove generic host keys, entrypoint generates unique keys
RUN echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk add --no-cache bash shadow@community openssh-server-pam openssh-sftp-server && \
    ln -s /usr/sbin/sshd.pam /usr/sbin/sshd && \
    mkdir -p /var/run/sshd && \
    rm -f /etc/ssh/ssh_host_*key*

RUN chmod -R 7777 /usr/
RUN chmod -R 7777 /var/run/
RUN chmod -R 7777 /etc
RUN chmod -R 7777 /etc/passwd

COPY files/sshd_config /etc/ssh/sshd_config
COPY files/create-sftp-user /usr/local/bin/
COPY files/entrypoint /
COPY files/user.conf /etc/sftp/users.conf

EXPOSE 22

ENTRYPOINT ["/entrypoint"]
